# File: Aulas-2025/_quarto.yml
project:
  type: default
  output-dir: _output

# Shared settings for all documents in this folder
format:
  revealjs:
    theme: [default, ../css/custom.scss]
    slide-number: true
    show-slide-number: all
    chalkboard: true

metadata:
  author: "Mikael Marin Coletto"
  date: "today"

editor: source

